parameters:
  - name: projectPath
    type: string
    default: '.'

  - name: folderName
    type: string
    default: ''

  - name: versioningStrategy
    type: string
    default: 'CurrentVersion'

  - name: environments
    type: string
    default: ''

stages:
- stage: Build
  jobs:
    - job: BuildJob
      pool:
        vmImage: 'windows-latest'

      workspace:
        clean: all

      steps:
        - script: |
            echo project path: ${{ parameters.projectPath }}
            echo folder name: ${{ parameters.folderName }}
            echo versioning strategy: ${{ parameters.versioningStrategy }}
            echo environments: ${{ parameters.environments }}
          displayName: 'Log Parameters'

        - task: UiPathInstallPlatform-preview@5

        - task: UiPathPack@5
          inputs:
            versionType: ${{ parameters.versioningStrategy }}
            projectJsonPath: '$(Build.SourcesDirectory)\${{ parameters.projectPath }}'
            orchestratorConnection: 'Uipath'
            outputPath: '$(Build.ArtifactStagingDirectory)\Output'

        - publish: '$(Build.ArtifactStagingDirectory)\Output'
          artifact: drop

# -------------------------------
# Deploy to Test (main or feature/*)
- stage: DeployToTest
  condition: and(
    succeeded('Build'),
    or(
      startsWith(variables['Build.SourceBranchName'], 'main'),
      startsWith(variables['Build.SourceBranchName'], 'feature')
    )
  )
  jobs:
    - job: DeployToTestJob
      pool:
        vmImage: 'windows-latest'

      workspace:
        clean: all

      steps:
        - download: current
          artifact: drop

        - task: UiPathInstallPlatform-preview@5

        - task: UiPathDeploy@5
          inputs:
            orchestratorConnection: 'Uipath'
            packagesPath: '$(Pipeline.Workspace)\drop'
            folderName: ${{ parameters.folderName }}
            environments: 'Test'

# -------------------------------
# Deploy to Prod (develop branch with approval)
- stage: DeployToProd
  condition: and(
    succeeded('Build'),
    eq(variables['Build.SourceBranchName'], 'develop')
  )
  jobs:
    - deployment: DeployToProdJob
      pool:
        vmImage: 'windows-latest'

      workspace:
        clean: all

      environment: Production

      strategy:
        runOnce:
          deploy:
            steps:
              - download: current
                artifact: drop

              - task: UiPathInstallPlatform-preview@5

              - task: UiPathDeploy@5
                inputs:
                  orchestratorConnection: 'Uipath'
                  packagesPath: '$(Pipeline.Workspace)\drop'
                  folderName: ${{ parameters.folderName }}
                  environments: 'Prod'
